package com.vycepay.admin.application.service;

import java.util.ArrayList;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

import com.vycepay.admin.config.AdminProperties;
import com.vycepay.common.exception.BusinessException;
import org.springframework.http.HttpStatus;
import org.springframework.jdbc.core.JdbcTemplate;
import org.springframework.stereotype.Service;

/** Provides read models and aggregate queries for admin list, detail, dashboard, and report screens. */
@Service
public class AdminReadService {
    private final JdbcTemplate jdbcTemplate;
    private final AdminSecurityContext securityContext;
    private final PiiMaskingService maskingService;
    private final AdminProperties properties;
    public AdminReadService(JdbcTemplate jdbcTemplate, AdminSecurityContext securityContext, PiiMaskingService maskingService, AdminProperties properties) { this.jdbcTemplate = jdbcTemplate; this.securityContext = securityContext; this.maskingService = maskingService; this.properties = properties; }

    public Map<String, Object> dashboardSummary() {
        Map<String, Object> m = new LinkedHashMap<>();
        m.put("totalCustomers", count("customer", "1=1"));
        m.put("activeWallets", count("wallet", "status='ACTIVE'"));
        m.put("todayTxVolume", jdbcTemplate.queryForObject("SELECT COALESCE(SUM(amount),0) FROM `transaction` WHERE DATE(created_at)=CURRENT_DATE", java.math.BigDecimal.class));
        m.put("todayTxCount", count("`transaction`", "DATE(created_at)=CURRENT_DATE"));
        m.put("kycApprovalRate", jdbcTemplate.queryForObject("SELECT COALESCE(ROUND(100 * SUM(status='APPROVED') / NULLIF(COUNT(*),0), 2), 0) FROM kyc_verification", java.math.BigDecimal.class));
        m.put("pendingCallbacks", count("choice_bank_callback", "processed=FALSE"));
        m.put("stuckTxOver1h", count("`transaction`", "status='PENDING' AND created_at < DATE_SUB(NOW(), INTERVAL 1 HOUR)"));
        return m;
    }
    public List<Map<String, Object>> txVolumeChart(int days) { return jdbcTemplate.queryForList("SELECT DATE(created_at) date, SUM(CASE WHEN type='TRANSFER' THEN amount ELSE 0 END) transferAmount, SUM(CASE WHEN type='DEPOSIT' THEN amount ELSE 0 END) depositAmount FROM `transaction` WHERE created_at >= DATE_SUB(CURRENT_DATE, INTERVAL ? DAY) GROUP BY DATE(created_at) ORDER BY date", days); }
    public Map<String, Object> txTypeDonut(int days) { return jdbcTemplate.queryForMap("SELECT SUM(type='TRANSFER') transferCount, SUM(type='DEPOSIT') depositCount, SUM(CASE WHEN type='TRANSFER' THEN amount ELSE 0 END) transferVolume, SUM(CASE WHEN type='DEPOSIT' THEN amount ELSE 0 END) depositVolume FROM `transaction` WHERE created_at >= DATE_SUB(CURRENT_DATE, INTERVAL ? DAY)", days); }
    public List<Map<String, Object>> kycStatusChart() { return jdbcTemplate.queryForList("SELECT status, COUNT(*) count FROM kyc_verification GROUP BY status ORDER BY count DESC"); }
    public Map<String, Object> alerts() { return Map.of("unprocessedCallbacks", count("choice_bank_callback", "processed=FALSE"), "pendingTxOver1h", count("`transaction`", "status='PENDING' AND created_at < DATE_SUB(NOW(), INTERVAL 1 HOUR)"), "pendingTxOver24h", count("`transaction`", "status='PENDING' AND created_at < DATE_SUB(NOW(), INTERVAL 24 HOUR)")); }
    public List<Map<String, Object>> recentTransactions(int limit) { return jdbcTemplate.queryForList("SELECT t.external_id externalId, t.type, t.amount, t.currency, t.status, t.created_at createdAt, c.external_id customerExternalId FROM `transaction` t JOIN customer c ON c.id=t.customer_id ORDER BY t.created_at DESC LIMIT ?", Math.min(Math.max(limit, 1), 50)); }

    public Map<String, Object> customers(Integer pageReq, Integer sizeReq, String search, String status) { int page=Pagination.page(pageReq), size=Pagination.size(sizeReq); Query q = customerQuery(search, status, false); List<Map<String,Object>> rows = jdbcTemplate.queryForList(q.sql + " ORDER BY c.created_at DESC LIMIT ? OFFSET ?", params(q.params, size, Pagination.offset(page,size))); maskCustomers(rows); long total = jdbcTemplate.queryForObject(customerQuery(search,status,true).sql, Long.class, q.params.toArray()); return Pagination.response(rows,page,size,total); }
    public Map<String, Object> customerDetail(String id) { var rows = jdbcTemplate.queryForList(customerQuery(id, null, false, true).sql, idParams(id)); if (rows.isEmpty()) throw notFound("CUSTOMER_NOT_FOUND"); Map<String,Object> row=rows.get(0); maskCustomer(row); return row; }
    public Map<String, Object> customerTransactions(String id, Integer pageReq, Integer sizeReq) { Long customerId = customerPk(id); return page("SELECT t.external_id externalId, t.type, t.amount, t.currency, t.status, t.created_at createdAt FROM `transaction` t WHERE t.customer_id=?", "SELECT COUNT(*) FROM `transaction` t WHERE t.customer_id=?", pageReq, sizeReq, customerId); }
    public Map<String, Object> customerKyc(String id) { Long customerId = customerPk(id); var rows=jdbcTemplate.queryForList("SELECT * FROM kyc_verification WHERE customer_id=?", customerId); if(rows.isEmpty()) return Map.of(); Map<String,Object> row=rows.get(0); boolean docs=securityContext.hasPermission("kyc:view_documents"); if(!docs){row.remove("id_front_url"); row.remove("selfie_url");} row.put("id_number", maskingService.maskIdNumber((String) row.get("id_number"), securityContext.hasPermission("customer:view_pii"))); return row; }
    public Map<String, Object> customerActivity(String id, Integer pageReq, Integer sizeReq) { Long customerId=customerPk(id); return page("SELECT id, action, resource_type resourceType, resource_id resourceId, created_at createdAt FROM activity_log WHERE customer_id=?", "SELECT COUNT(*) FROM activity_log WHERE customer_id=?", pageReq, sizeReq, customerId); }

    public Map<String, Object> kyc(Integer pageReq, Integer sizeReq, String status, String search) { String where="1=1"; List<Object> p=new ArrayList<>(); if(status!=null&&!status.isBlank()){where+=" AND k.status=?";p.add(status);} if(search!=null&&!search.isBlank()){where+=" AND (c.external_id LIKE ? OR c.mobile LIKE ? OR k.choice_onboarding_request_id LIKE ?)";String s="%"+search+"%";p.add(s);p.add(s);p.add(s);} return page("SELECT k.id, k.choice_onboarding_request_id choiceOnboardingRequestId, k.status, k.id_type idType, k.created_at createdAt, c.external_id customerExternalId, c.first_name firstName, c.last_name lastName FROM kyc_verification k JOIN customer c ON c.id=k.customer_id WHERE "+where, "SELECT COUNT(*) FROM kyc_verification k JOIN customer c ON c.id=k.customer_id WHERE "+where, pageReq, sizeReq, p.toArray()); }
    public Map<String, Object> kycDetail(Long id) { var rows=jdbcTemplate.queryForList("SELECT k.*, c.external_id customerExternalId, c.first_name firstName, c.last_name lastName FROM kyc_verification k JOIN customer c ON c.id=k.customer_id WHERE k.id=?", id); if(rows.isEmpty()) throw notFound("KYC_NOT_FOUND"); Map<String,Object> row=rows.get(0); if(!securityContext.hasPermission("kyc:view_documents")){row.remove("id_front_url");row.remove("selfie_url");} row.put("id_number", maskingService.maskIdNumber((String) row.get("id_number"), securityContext.hasPermission("customer:view_pii"))); return row; }
    public Map<String, Object> wallets(Integer pageReq, Integer sizeReq, String search, String status) { String where="1=1"; List<Object> p=new ArrayList<>(); if(status!=null&&!status.isBlank()){where+=" AND w.status=?";p.add(status);} if(search!=null&&!search.isBlank()){where+=" AND (c.external_id LIKE ? OR c.mobile LIKE ? OR w.choice_account_id LIKE ?)";String s="%"+search+"%";p.add(s);p.add(s);p.add(s);} Map<String,Object> res=page("SELECT w.id, w.choice_account_id choiceAccountId, w.balance_cache balance, w.currency, w.status, c.external_id customerExternalId, c.mobile_country_code mobileCountryCode, c.mobile FROM wallet w JOIN customer c ON c.id=w.customer_id WHERE "+where, "SELECT COUNT(*) FROM wallet w JOIN customer c ON c.id=w.customer_id WHERE "+where, pageReq, sizeReq, p.toArray()); ((List<Map<String,Object>>)res.get("content")).forEach(this::maskCustomer); return res; }
    public Map<String, Object> walletDetail(Long id) { var rows=jdbcTemplate.queryForList("SELECT w.*, c.external_id customerExternalId, c.mobile_country_code mobileCountryCode, c.mobile FROM wallet w JOIN customer c ON c.id=w.customer_id WHERE w.id=?", id); if(rows.isEmpty()) throw notFound("WALLET_NOT_FOUND"); Map<String,Object> row=rows.get(0); maskCustomer(row); return row; }
    public Map<String, Object> transactions(Integer pageReq, Integer sizeReq, String type, String status, String search) { String where="1=1"; List<Object> p=new ArrayList<>(); if(type!=null&&!type.isBlank()){where+=" AND t.type=?";p.add(type);} if(status!=null&&!status.isBlank()){where+=" AND t.status=?";p.add(status);} if(search!=null&&!search.isBlank()){where+=" AND (t.external_id LIKE ? OR t.choice_request_id LIKE ? OR c.external_id LIKE ?)";String s="%"+search+"%";p.add(s);p.add(s);p.add(s);} return page("SELECT t.external_id externalId, t.choice_request_id choiceRequestId, t.type, t.amount, t.currency, t.status, t.error_code errorCode, t.error_msg errorMsg, t.created_at createdAt, c.external_id customerExternalId FROM `transaction` t JOIN customer c ON c.id=t.customer_id WHERE "+where, "SELECT COUNT(*) FROM `transaction` t JOIN customer c ON c.id=t.customer_id WHERE "+where, pageReq, sizeReq, p.toArray()); }
    public Map<String, Object> transactionDetail(String id) { var rows=jdbcTemplate.queryForList("SELECT t.*, c.external_id customerExternalId, w.choice_account_id choiceAccountId FROM `transaction` t JOIN customer c ON c.id=t.customer_id JOIN wallet w ON w.id=t.wallet_id WHERE t.external_id=? OR t.id=?", id, numericId(id)); if(rows.isEmpty()) throw notFound("TX_NOT_FOUND"); return rows.get(0); }
    public Map<String, Object> failedTransactions(Integer pageReq, Integer sizeReq, String errorCode) { String where="t.status='FAILED'"; List<Object> p=new ArrayList<>(); if(errorCode!=null&&!errorCode.isBlank()){where+=" AND t.error_code=?";p.add(errorCode);} return page("SELECT t.external_id externalId, t.type, t.amount, t.currency, t.status, t.error_code errorCode, t.error_msg errorMsg, t.created_at createdAt FROM `transaction` t WHERE "+where, "SELECT COUNT(*) FROM `transaction` t WHERE "+where, pageReq, sizeReq, p.toArray()); }
    public Map<String, Object> callbacks(Integer pageReq, Integer sizeReq, String type, Boolean processed) { String where="1=1"; List<Object> p=new ArrayList<>(); if(type!=null&&!type.isBlank()){where+=" AND notification_type=?";p.add(type);} if(processed!=null){where+=" AND processed=?";p.add(processed);} return page("SELECT id, choice_request_id choiceRequestId, notification_type notificationType, processed, processed_at processedAt, processing_error processingError, created_at createdAt FROM choice_bank_callback WHERE "+where, "SELECT COUNT(*) FROM choice_bank_callback WHERE "+where, pageReq, sizeReq, p.toArray()); }
    public Map<String, Object> callbackDetail(Long id) { var rows=jdbcTemplate.queryForList("SELECT * FROM choice_bank_callback WHERE id=?", id); if(rows.isEmpty()) throw notFound("CALLBACK_NOT_FOUND"); Map<String,Object> row=rows.get(0); if(!securityContext.hasPermission("callback:view")){row.remove("raw_payload");} return row; }
    public List<Map<String,Object>> reportVolume(String groupBy) { String fmt = "month".equals(groupBy) ? "%Y-%m" : "week".equals(groupBy) ? "%x-W%v" : "%Y-%m-%d"; return jdbcTemplate.queryForList("SELECT DATE_FORMAT(created_at, ?) period, SUM(CASE WHEN type='TRANSFER' THEN amount ELSE 0 END) transferVol, SUM(CASE WHEN type='DEPOSIT' THEN amount ELSE 0 END) depositVol, COUNT(*) txCount FROM `transaction` GROUP BY DATE_FORMAT(created_at, ?) ORDER BY period", fmt, fmt); }
    public Map<String,Object> reportKycFunnel() { return jdbcTemplate.queryForMap("SELECT SUM(status IS NOT NULL) submitted, SUM(status='OTP_SENT') otpSent, SUM(status='OTP_CONFIRMED') otpConfirmed, SUM(status='PENDING') pending, SUM(status='APPROVED') approved, SUM(status='REJECTED') rejected FROM kyc_verification"); }
    public List<Map<String,Object>> reportGrowth(String groupBy) { String fmt = "month".equals(groupBy) ? "%Y-%m" : "week".equals(groupBy) ? "%x-W%v" : "%Y-%m-%d"; return jdbcTemplate.queryForList("SELECT DATE_FORMAT(created_at, ?) period, COUNT(*) newCustomers, SUM(COUNT(*)) OVER (ORDER BY DATE_FORMAT(created_at, ?)) cumulativeTotal FROM customer GROUP BY DATE_FORMAT(created_at, ?) ORDER BY period", fmt, fmt, fmt); }
    public Map<String,Object> auditLog(Integer pageReq, Integer sizeReq, String action) { String where="1=1"; List<Object> p=new ArrayList<>(); if(action!=null&&!action.isBlank()){where+=" AND action=?";p.add(action);} return page("SELECT id, customer_id customerId, action, resource_type resourceType, resource_id resourceId, created_at createdAt FROM activity_log WHERE "+where, "SELECT COUNT(*) FROM activity_log WHERE "+where, pageReq, sizeReq, p.toArray()); }
    public Map<String,Object> adminAuditLog(Integer pageReq, Integer sizeReq, String action) { String where="1=1"; List<Object> p=new ArrayList<>(); if(action!=null&&!action.isBlank()){where+=" AND a.action=?";p.add(action);} return page("SELECT a.id, a.action, a.entity_type entityType, a.entity_id entityId, a.reason, a.created_at createdAt, u.username adminUsername FROM admin_audit_log a JOIN admin_user u ON u.id=a.admin_user_id WHERE "+where, "SELECT COUNT(*) FROM admin_audit_log a WHERE "+where, pageReq, sizeReq, p.toArray()); }
    public List<Map<String,Object>> menus() { return jdbcTemplate.queryForList("SELECT id, name, route, icon, parent_id parentId, sort_order sortOrder FROM admin_menu ORDER BY COALESCE(parent_id, id), sort_order"); }
    public List<Map<String,Object>> roles() { return jdbcTemplate.queryForList("SELECT r.id, r.name, r.description, COUNT(DISTINCT rm.menu_id) menuCount, COUNT(DISTINCT rp.permission_id) permissionCount FROM admin_role r LEFT JOIN admin_role_menu rm ON rm.role_id=r.id LEFT JOIN admin_role_permission rp ON rp.role_id=r.id GROUP BY r.id ORDER BY r.name"); }
    public Map<String,Object> roleDetail(Long id) { Map<String,Object> r=jdbcTemplate.queryForMap("SELECT id, name, description FROM admin_role WHERE id=?", id); r.put("menuIds", jdbcTemplate.queryForList("SELECT menu_id FROM admin_role_menu WHERE role_id=?", Long.class, id)); r.put("permissionCodes", jdbcTemplate.queryForList("SELECT p.code FROM admin_role_permission rp JOIN admin_permission p ON p.id=rp.permission_id WHERE rp.role_id=?", String.class, id)); return r; }
    public Map<String,Object> adminUsers(Integer pageReq, Integer sizeReq) { return page("SELECT id, external_id externalId, username, email, full_name fullName, status, last_login_at lastLoginAt FROM admin_user", "SELECT COUNT(*) FROM admin_user", pageReq, sizeReq); }
    public Map<String,Object> adminUser(Long id) { Map<String,Object> u=jdbcTemplate.queryForMap("SELECT id, external_id externalId, username, email, full_name fullName, status, last_login_at lastLoginAt FROM admin_user WHERE id=?", id); u.put("roleIds", jdbcTemplate.queryForList("SELECT role_id FROM admin_user_role WHERE user_id=?", Long.class, id)); return u; }
    public List<Map<String,Object>> permissions() { return jdbcTemplate.queryForList("SELECT code, description FROM admin_permission ORDER BY code"); }

    private long count(String table, String where) { Long v=jdbcTemplate.queryForObject("SELECT COUNT(*) FROM "+table+" WHERE "+where, Long.class); return v==null?0:v; }
    private Map<String,Object> page(String select, String count, Integer pageReq, Integer sizeReq, Object... params) { int page=Pagination.page(pageReq), size=Pagination.size(sizeReq); List<Object> p=new ArrayList<>(List.of(params)); List<Object> listParams=new ArrayList<>(p); listParams.add(size); listParams.add(Pagination.offset(page,size)); List<Map<String,Object>> rows=jdbcTemplate.queryForList(select+" ORDER BY 1 DESC LIMIT ? OFFSET ?", listParams.toArray()); long total=jdbcTemplate.queryForObject(count, Long.class, p.toArray()); return Pagination.response(rows,page,size,total); }
    private Query customerQuery(String search, String status, boolean count) { return customerQuery(search,status,count,false); }
    private Query customerQuery(String search, String status, boolean count, boolean detail) { String select=count?"SELECT COUNT(*)":"SELECT c.id, c.external_id externalId, c.mobile_country_code mobileCountryCode, c.mobile, c.email, c.first_name firstName, c.last_name lastName, c.status, c.created_at createdAt, w.balance_cache walletBalance, w.status walletStatus, k.status kycStatus"; String sql=select+" FROM customer c LEFT JOIN wallet w ON w.customer_id=c.id LEFT JOIN kyc_verification k ON k.customer_id=c.id WHERE 1=1"; List<Object> p=new ArrayList<>(); if(detail){sql+=" AND (c.external_id=? OR c.id=?)";} else { if(status!=null&&!status.isBlank()){sql+=" AND c.status=?";p.add(status);} if(search!=null&&!search.isBlank()){sql+=" AND (c.external_id LIKE ? OR c.mobile LIKE ? OR c.email LIKE ? OR c.first_name LIKE ? OR c.last_name LIKE ?)";String s="%"+search+"%";p.add(s);p.add(s);p.add(s);p.add(s);p.add(s);} } return new Query(sql,p); }
    private Object[] idParams(String id){ return new Object[]{id,numericId(id)}; }
    private Long numericId(String id){ try{return Long.parseLong(id);}catch(Exception e){return -1L;} }
    private Long customerPk(String id){ var rows=jdbcTemplate.queryForList("SELECT id FROM customer WHERE external_id=? OR id=?", id, numericId(id)); if(rows.isEmpty()) throw notFound("CUSTOMER_NOT_FOUND"); return ((Number)rows.get(0).get("id")).longValue(); }
    private void maskCustomers(List<Map<String,Object>> rows){ rows.forEach(this::maskCustomer); }
    private void maskCustomer(Map<String,Object> row){ boolean pii=securityContext.hasPermission("customer:view_pii"); row.put("mobile", maskingService.maskMobile((String)row.get("mobileCountryCode"), (String)row.get("mobile"), pii)); }
    private BusinessException notFound(String code){ return new BusinessException(code, "Resource not found", HttpStatus.NOT_FOUND); }
    private Object[] params(List<Object> base, Object... tail){ List<Object> all=new ArrayList<>(base); all.addAll(List.of(tail)); return all.toArray(); }
    private record Query(String sql, List<Object> params) {}
}
