export const navItems = [
  { label: 'Dashboard', href: '/dashboard' },
  { label: 'Customers', href: '/customers' },
  { label: 'KYC', href: '/kyc' },
  { label: 'Wallets', href: '/wallets' },
  { label: 'Transactions', href: '/transactions' },
  { label: 'Failed Transactions', href: '/transactions/failed' },
  { label: 'Callbacks', href: '/callbacks' },
  { label: 'Volume Report', href: '/reports/volume' },
  { label: 'KYC Funnel', href: '/reports/kyc-funnel' },
  { label: 'Customer Growth', href: '/reports/growth' },
  { label: 'Audit Log', href: '/audit-log' },
  { label: 'System Health', href: '/system-health' },
  { label: 'Menus', href: '/admin/menus' },
  { label: 'Roles', href: '/admin/roles' },
  { label: 'Admin Users', href: '/admin/users' },
]
